### PR TITLE
adds fix to respect translation for header and nav blocks

### LINKED ISSUE #144: Guide title block and Guide Navigation links are not respecting translations
If you have a guide overview in English and Irish, and then some guide pages in English and Irish, when you look at guide pages, the page title block and the guide navigation return the English version only.

PR on the way.

### PR DESCRIPTION
**Pull request by markconroy**
Closes #144

### CODE REVIEW

**Review by ekes — CHANGES_REQUESTED** [review]
You know during drop-in I was trying to remember what the one-line way of getting the translated entity was, but just couldn't remember:

[EntityRepositoryInterface::getTranslationFromContext](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21EntityRepositoryInterface.php/function/EntityRepositoryInterface%3A%3AgetTranslationFromContext/8.2.x)

There are a few reasons to use this in preference to getting the current language and requesting the translation:

- The EntityRepository service [uses the fallback language settings](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/lib/Drupal/Core/Entity/EntityRepository.php?ref_type=heads#L107) to get the most appropriate translation;
- Additionally the service is designed to default to the interface language, adds some appropriate cache tags;
- Getting the entity translation, on the other hand, [makes a clone of the original ](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/lib/Drupal/Core/Entity/ContentEntityBase.php?ref_type=heads#L898) default language if the translation doesn't exist. So this is more useful if you are wanting to create, or update, a translation of an entity.

So using `\Drupal::service('entity.repository')->getTranslationFromContext($entity)`, or the appropriate equivalent having loaded `entity.repository` by dependency injection, would seem to be the better way of getting the desired translation.

**Comment by ekes** [comment]
Just 9.4 failing. Should be removed from test matrix.

@markconroy I've just written the code, not tested it, do you want to check this still works for your site?
@stephen-cox Do you want to do an eye code check?

Then we could merge?

**Comment by finnlewis** [comment]
@markconroy could you check this still does what it should?

**Comment by finnlewis** [comment]
Closing this in favour of #157

**Pull request closed without merging**
