### PR TITLE
Fix prev / next unpublish #44

### LINKED ISSUE #44: Unpublished pages showing on GuidePrevNextBlock
Similar to https://github.com/localgovdrupal/localgov_guides/pull/27, unpublished pages are showing in the prev/next block. 

Propose to add a similar access check so the block doesn't render these pages to unauthorised users.

### PR DESCRIPTION
**Pull request by ekes**
Fixes #44 

#45 wouldn't show a prev/next if an adjacent page was unpublished. By moving the view access logic to the base block class the list of available pages is calculated for both blocks and the prev next can use the same calculation.

### CODE REVIEW

**Comment by ekes** [comment]
> test
> Your requirements could not be resolved to an installable set of packages.
>
> Problem 1
>   - brianium/paratest 4.0.0 requires php ^7.1 -> your php version (8.0.3) does not satisfy that requirement.
>    - brianium/paratest[4.1.0, ..., 4.2.0] require php ^7.3 -> your php version (8.0.3) does not satisfy that requirement.
>    - Root composer.json requires brianium/paratest ^4.0.0 -> satisfiable by brianium/paratest[4.0.0, ..., 4.2.0

I thought the PHP 8 thing had been solved. Does something need pulling/adding from somewhere?

**Comment by ekes** [comment]
So I merged #42 which got over the PHP bump.

The fail however I can't now see.

> OK (80 tests, 1214 assertions)
> Error: Process completed with exit code 1.

**Comment by andybroomfield** [comment]
@ekes Is the thing I'm testing making sure an upublished guide page skips over in next / previous?

**Review by andybroomfield — APPROVED** [review]
Have tested this by creating a bunch of guide pages and unpublishing selected versions on the next / previous skips as appropriately.

Checked local, but I assume this won't have cache issues as the blocks caching tags are based on node ids of all guide pages?

**Comment by ekes** [comment]
Cache tags are set in the block base shared by PrevNext and Contents blocks, I'd assumed they were correct for the ContentsBlock which already excluded the unpublished pages.

**Comment by ekes** [comment]
@andybroomfield guess https://github.com/localgovdrupal/localgov_guides/pull/47/commits/4e3b9d796968a95afc044d5eac522f6ec8a07e8c covers any cache concern. Tags remain node:#ids_of_page_listed.

**Pull request merged**
