### PR TITLE
Use the dedicated guide description field as the lede in the page header block

### LINKED ISSUE #33: Fix the guide page title to use the dedicated guide description field (or remove it).
Currently guide pages use the guide overview body summary for the lede (summary) on the page header block.
There is however a dedicated Guide Description field, at BHCC, this dedicated field is used for the guide description and in summaries. However that is different to all other content types and even at BHCC the guide description and summary are duplicated. Is there any reason to keep it?

If it is to be kept, the page header block needs to be updated for guides to use the dedicated description field, else we should remove the field entirly.

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #33.

See issue there before merging, as this might not be the right solution, and it may be prefferable to delete the dedicated description field.

### CODE REVIEW

**Comment by finnlewis** [comment]
What's the status of this one @andybroomfield  @tanc ? I see it is still draft.

Tests pass and it looks to solve the problem in #33 

@Adnan-cds would this affect your usage at all?

**Comment by andybroomfield** [comment]
@finnlewis I think the question was do we want to use the dedicated description field or use the body summary like on all the other content types.

**Comment by Adnan-cds** [comment]
> I think the question was do we want to use the dedicated description field or use the body summary like on all the other content types.

Tom, Will, have you got any opinion on this?

FAO @tom-steel @willguv

**Comment by willguv** [comment]
Hi @Adnan-cds, I'm not sure what the description field is used for. Where does this content show please?

My pref (dunno about @tom-steel and others) is to make the content formats more consistent in the way they behave. 

Depending on what description is used for, I'd say use summary for descriptive copy underneath a page title, and any copy on the landing page above.

**Comment by andybroomfield** [comment]
@willguv @tom-steel See the issue in #33.
Basically Guide overview pages use a seperate field for the summary that goes below the title, but every other content type uses the body summary field to do the same thing.
So either:
- We want the dedicated descriptions field (Merge this PR)
- We want to keep using the Body summary field consistently on all content types (Delete the description field instead).

Hope that clears things up.

**Review by stephen-cox — APPROVED** [review]
This makes sense to me and works well.

**Comment by andybroomfield** [comment]
@stephen-cox @willguv @tom-steel did we resolve whether it was this fix we wanted to implement, or keep everything using body summaries?

**Comment by willguv** [comment]
@andybroomfield I think this content type needs to work in the same way as all of the others
 
ie https://localgovdrupal.slack.com/archives/C01TS349XCY/p1619527236002000

Do you agree @tom-steel? 

(We need a few more product and content people on Github ideally. Or can take this to Slack if there isn't consensus here)

**Comment by andybroomfield** [comment]
Ok, so it is not this Pull Request that merges, but we need to create another one that removes the description field and enables the body summary field.

**Comment by andybroomfield** [comment]
Reflagging this one.
Can we decide what we want to do? Remove the Guide description field and force show the summary, or make sure guides use the dedicated description field (This PR)

**Comment by willguv** [comment]
@andybroomfield thanks for flagging - would be good to resolve this v soon. 

I’m still keen to keep things consistent and have every content type use summaries in the same way. Is it likely that some councils have used the description field and have no content in the summary? If so, what’s the best way to address this?

Separately I’d like a group of content designers to review each format to check we’re doing things in consistent ways. Every time I see “common tasks” and “task buttons” it bugs me, for example. I’ll add another card.

Copying @danchamp as we talked about this previously.

**Comment by finnlewis** [comment]
@andybroomfield  @willguv  what needs to happen on this?

**Comment by andybroomfield** [comment]
@finnlewis I think this one needs to be closed and a new PR should be added to make the summary field visible on guide overview pages and the guide description field removed. There then needs to be an update hook to move any data in the guide description field into the body summary field.

**Comment by willguv** [comment]
@finnlewis I'd like to understand what will happen if we remove the description field and use the summary field. What happens if some councils have added text to the description and not the summary?

Thanks

**Comment by willguv** [comment]
@finnlewis I was commenting at the same time as @andybroomfield. Agree with his comment - thanks

**Comment by finnlewis** [comment]
@andybroomfield suggests we close this and open another PR to make guides work the same as all other content types with summary field.

**Pull request closed without merging**
