### PR TITLE
Add label and class to unpublished guide titles in guide contents block

### LINKED ISSUE #465: Highlight unpublished Guide pages
At the moment, unpublished Guide pages appear within the Guide content table when the viewer has editing rights to the Guide. This is not good UX as what the editor sees is not what a nonlogged in user sees. For better UX, such unpublished Guide pages should be clearly highlighted. We have similar highlighting for unpublished Service pages listed within Service (sub)landing pages.

[Example Guide](https://lbc-app-w-localgov-corpwebsite-p.azurewebsites.net/housing/home-owners-and-leaseholders/staying-put-service) where the Staying put Guide page is listed but unpublished.

This feature should become part of the localgov_guides module.

### PR DESCRIPTION
**Pull request by danchamp**
Closes localgovdrupal/localgov_base#465, this PR:

- Adds the text ' (Unpublished)' to unpublished guide titles in the guide contents block
- Adds the class `unpublished` to unpublished guide title links in the guide contents block

This assists content editors in recognising guide pages that appear in nav but aren't published.

A further PR for the localgov_base theme will extend BEM classes to allow styling of active **and** linked unpublished guide titles based on the presence of the `unpublished` class.

### CODE REVIEW

**Comment by finnlewis** [comment]
@danchamp I just merged back from the 2.x branch to bring in the latest changes and set it to ready for review, to see how the tests do now, hope that's OK!  Just trying to bring as many pull requests on in for the end of sprint 10 tomorrow.

**Comment by finnlewis** [comment]
@danchamp @Adnan-cds just discussing this in "Merge Monday".

@andybroomfield wonders if this might be fixed since updating the permissions on unpublished nodes.

**Comment by andybroomfield** [comment]
I was reffering to this PR https://github.com/localgovdrupal/localgov/pull/336 as now its merged refferencing unpublished entites should now be possible, so this can be looked at again.

**Comment by finnlewis** [comment]
@danchamp is this still relevant?

**Comment by finnlewis** [comment]
Hey @danchamp  - bumping this... still relevant or shall we close it?

**Comment by danchamp** [comment]
@finnlewis It's still relevant insofar as the issue remains - there's nothing to distinguish between published and unpublished guide pages when viewing a guide overview as an editor.

Sorry for the delay in replying, I'll take a look at this later this week if needed.

**Comment by finnlewis** [comment]
OK, thanks @danchamp  - I've merge 2.x branch back into this branch and pushed to trigger the tests against the latest test configuration.

**Comment by finnlewis** [comment]
@ekes mentioned today that it would be good to add a test for this.

**Comment by finnlewis** [comment]
Also need to fix the failing tests: undefined index 'attributes'

**Comment by finnlewis** [comment]
@danchamp this still sounds useful, but before I dive in to try to fix the tests, just checking that this is still valuable from your perspective? I'm sure we can resolve.

**Comment by markconroy** [comment]
I'm going to close this issue. I think it's fixed by the "theme options for unpublished pages" feature we built for `localgov_base` - https://github.com/localgovdrupal/localgov_base/pull/500

**Pull request closed without merging**
