### PR TITLE
Fix: Guide overview subtitle

### LINKED ISSUE #113: Make the word 'overview' editable
This issue was discussed and agreed in the new content design monthly Meetup today.

When you add a guide overview, the word 'overview' appears at the first page, and you cannot change it. Almost every council has amended this so they can change it.

The request is to make this editable in the core theme for everyone

### PR DESCRIPTION
**Pull request by Adnan-cds**
Replacing hardcoded subtitle with Guide section title.

Resolves #113

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Test run failing due to [issues beyond](https://github.com/localgovdrupal/localgov_guides/actions/runs/5365751007/jobs/9734766415?pr=120#step:11:28) this pull request.

**Comment by stephen-cox** [comment]
> Test run failing due to [issues beyond](https://github.com/localgovdrupal/localgov_guides/actions/runs/5365751007/jobs/9734766415?pr=120#step:11:28) this pull request.

Tests are running again :smile:

**Comment by Adnan-cds** [comment]
> Tests are running again

Thanks a lot for resolving this :)

**Review by stephen-cox — APPROVED** [review]
Works for me

**Comment by Adnan-cds** [comment]
Thanks for testing and approving.  Merging...

**Pull request merged**
