### PR TITLE
Initialise guidePages as an array as it is used within array_filter even though it starts of as null

### PR DESCRIPTION
**Pull request by benlamptey**
Without this, new `Guide overview` pages display an error.

```
TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in array_filter() (line 113 of modules/contrib/localgov_guides/src/Plugin/Block/GuidesAbstractBaseBlock.php).
```

### CODE REVIEW

**Comment by louwrense** [comment]
@finnlewis @ekes We found last week that a Guide Overview page cannot be viewed on the FE unless it has at least one Guide page added to it. Otherwise we see the error. This update from Ben allows us to view a guide overview page that has no children yet.

**Comment by ekes** [comment]
@finnlewis This makes sense so we should get it merged today.

I just don't understand where the PR for https://github.com/localgovdrupal/localgov_guides/commit/b6f041ff447c442222509a0cbf8e52cac098cfb9 went? That is related right?

**Comment by finnlewis** [comment]
Thanks @benlamptey , @louwrense and @ekes 

Yes, I don't think I had made a pull request for that test. 

Here's a pull request that adds a test that should fail without this one https://github.com/localgovdrupal/localgov_guides/pull/161

**Review by stephen-cox — APPROVED** [review]
Can confirm this fixes the issue

**Pull request merged**
